Minor fixes
whatsnew.omh: user's view of the changes.
Build: automate checking more things during Build test.
Makefile.am: tell automake to look for omh/getstarted/makefile.am.
RunOMhelp: always return status flag.
configure.ac: add fortran compiler and omh/getstarted/makefile.am.
overview.omh: make sure looks in omh/getstarted for *.c and *.f.
near_equal.c: move test to separate file.
near_equal.f: move test to separate file.
run_all.sh: change from Factorial.* to near_equal.*.
view_near_equal.c.omh: verbatim file reference relation to getstarted dir.
view_near_equal.f.omh: verbatim file reference relation to getstarted dir.
makefile.am: for building test of Fortran and C routines.
ok_near_equal.c: test of near_equal.c.
ok_near_equal.f: test of near_equal.f.
run_all.c: run all tests of Fortran and C routines.

----------------------------------------------------------------------
Edit section above for individual cases, section below stays the same
----------------------------------------------------------------------

diff --git a/Build b/Build
--- a/Build
+++ b/Build
@@ -306,15 +306,30 @@ then
 	cd omhelp-$AcDate
 	./Build configure
 	make
-	if [ "$1" != "all" ]
+	if ! ./RunOMhelp Doc
 	then
-		exit
+		echo "user doc problem; see omhelp-$AcDate/OMhelp.Doc.log"
+		exit 1
+	fi
+	if ! ./RunOMhelp Dev
+	then
+		echo "dev doc problem; see omhelp-$AcDate/OMhelp.Dev.log"
+		exit 1
 	fi
 	cd omh/getstarted
 	if ! ./run_all.sh batch
 	then
-		echo "omh/getstarted/run_all failed to run"
+		echo "omh/getstarted/run_all.sh failed to run"
 		exit 1
+	fi
+	if ! ./run_all
+	then
+		echo "one of the tests in omh/getstarted/run_all.c failed"
+		exit 1
+	fi
+	if [ "$1" != "all" ]
+	then
+		exit
 	fi
 fi
 if [ "$1" = "all" ]
