Specify the OMhelp exit status.
CvsCommit: file that did this commit.
RunOMhelp: abort with status 1 when OMhelp reports an error.
running.omh: document status return.
whatsnew.omh: user's view of the changes.
Makefile.am: trace_exit.c was added to sources (include files not needed).
allocate.c: use trace_exit for exit calls.
allocmem.c: use trace_exit for exit calls.
fatalerr.c: use trace_exit for exit calls.
lexomh.c: fix comamnd -> command in error message.
main.src: use trace_exit for exit calls.
spell.c: use trace_exit for exit calls.
src.vcproj: add trace_exit.c to soruces.
trace_exit.c: optional trace of calls to exit.
trace_exit.h: optional trace of calls to exit.
----------------------------------------------------------------------
Edit section above for individual cases, section below stays the same
----------------------------------------------------------------------

diff --git a/RunOMhelp b/RunOMhelp
--- a/RunOMhelp
+++ b/RunOMhelp
@@ -31,8 +31,12 @@ then
 	fi
 	mkdir Developer
 	cd    Developer
-	../src/omhelp ../src/omh/omhelp.omh > ../RunOMhelp.log \
+	if ! ../src/omhelp ../src/omh/omhelp.omh > ../RunOMhelp.log \
 		-debug -omhelp_dir ../OMhelp
+	then
+		echo "OMhelp could not build developer documentation."
+		exit 1
+	fi
 	cd ..
 fi
 if [ "$1" = Doc ]
@@ -44,17 +48,12 @@ then
 	fi
 	mkdir Doc
 	cd    Doc
-	../src/omhelp ../omh/overview.omh > ../RunOMhelp.log \
+	if ! ../src/omhelp ../omh/overview.omh > ../RunOMhelp.log \
 		-xml -debug -omhelp_dir ../OMhelp
+	then
+		echo "OMhelp could not build user documentation."
+		exit 1
+	fi
 	../src/omhelp ../omh/overview.omh  -debug -omhelp_dir ../OMhelp
 	cd ..
 fi
-status=0
-if grep "Latex error"                 RunOMhelp.log ; then status=1 ; fi
-if grep "Spelling error:"             RunOMhelp.log ; then status=1 ; fi
-if grep "Cross reference error"       RunOMhelp.log ; then status=1 ; fi
-if grep "OMhelp error in file"        RunOMhelp.log ; then status=1 ; fi
-if grep "Error occurred in or before" RunOMhelp.log ; then status=1 ; fi
-if grep "Cross reference destination" RunOMhelp.log ; then status=1 ; fi
-#
-exit $status
